name: docker

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: third-party-api-resolver-server
          tags: ${{ github.sha }} next
          dockerfiles: |
            ./Dockerfile
      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/decentraland
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

      - name: Trigger deployment - dev
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: '${{ steps.push-to-quay.outputs.registry-path }}'
          serviceName: third-party-api-resolver-server
          env: dev
          token: ${{ secrets.GITHUB_TOKEN }}
